# Generated by Django 5.2.17 on 2026-10-08 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_smsotpchallenge'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SMSOTPChallenge',
        ),
    ]
