# Generated by Django 5.2.17 on 2026-10-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_requests', '0002_support_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportrequesthistory',
            name='from_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('DOCUMENTS_REQUIRED', 'Additional Information / Documents Required'), ('APPROVED', 'Approved'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], max_length=25),
        ),
        migrations.AlterField(
            model_name='supportrequesthistory',
            name='to_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('DOCUMENTS_REQUIRED', 'Additional Information / Documents Required'), ('APPROVED', 'Approved'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], max_length=25),
        ),
    ]
