# Generated by Django 5.2.17 on 2026-10-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosques', '0002_mosqueoperationalprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mosque',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Pending Platform Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='DRAFT', max_length=25),
        ),
        migrations.AlterField(
            model_name='mosquereviewhistory',
            name='from_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Pending Platform Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=25),
        ),
        migrations.AlterField(
            model_name='mosquereviewhistory',
            name='to_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Pending Platform Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=25),
        ),
    ]
